"""商品名称不唯一，ID唯一

Revision ID: 33af9a2e191c
Revises: 99a46abfac7c
Create Date: 2023-12-26 16:11:23.836497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.services.auth_service import get_password_hash


# revision identifiers, used by Alembic.
revision: str = '33af9a2e191c'
down_revision: Union[str, None] = '99a46abfac7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_info', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='商品名称')
    op.drop_constraint('goods_info_name_key', 'goods_info', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('goods_info_name_key', 'goods_info', ['name'])
    op.alter_column('goods_info', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='商品名称')
    # ### end Alembic commands ###
