"""商品信息表新增属性

Revision ID: c1df3bc26c57
Revises: f4b8152a4bb2
Create Date: 2023-12-25 14:53:29.526259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.services.auth_service import get_password_hash


# revision identifiers, used by Alembic.
revision: str = 'c1df3bc26c57'
down_revision: Union[str, None] = 'f4b8152a4bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_info', sa.Column('variety', sa.String(length=50), nullable=True, comment='品种'))
    op.add_column('goods_info', sa.Column('color', sa.String(length=50), nullable=True, comment='花色'))
    op.add_column('goods_info', sa.Column('occasion', sa.String(length=50), nullable=False, comment='使用场合'))
    op.alter_column('goods_info', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='商品描述',
               existing_comment='描述')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_info', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='描述',
               existing_comment='商品描述')
    op.drop_column('goods_info', 'occasion')
    op.drop_column('goods_info', 'color')
    op.drop_column('goods_info', 'variety')
    # ### end Alembic commands ###
